import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 20,
    color: '#111827',
  },
  metricsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  metricCard: {
    padding: 15,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    width: '30%',
    alignItems: 'center',
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 10,
    color: '#6B7280',
    textTransform: 'uppercase',
  },
  tweetRow: {
    marginBottom: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 6,
  },
  tweetContent: {
    fontSize: 10,
    color: '#374151',
    marginBottom: 8,
    lineHeight: 1.4,
  },
  tweetMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    paddingTop: 8,
  },
  tweetStat: {
    fontSize: 9,
    color: '#6B7280',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: '#9CA3AF',
  },
});

export interface AnalyticsPdfData {
  range: string;
  totals: {
    impressions: number;
    likes: number;
    retweets: number;
    replies: number;
    linkClicks: number;
  };
  topTweets: Array<{
    content: string;
    impressions: number;
    likes: number;
    retweets: number;
    replies: number;
    fetchedAt: Date;
  }>;
}

export const AnalyticsPdfDocument = ({ data }: { data: AnalyticsPdfData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>AstroPost Analytics</Text>
          <Text style={styles.subtitle}>Performance Report ({data.range})</Text>
        </View>
        <Text style={styles.subtitle}>{new Date().toLocaleDateString()}</Text>
      </View>

      {/* Summary Metrics */}
      <View style={styles.metricsContainer}>
        <View style={styles.metricCard}>
          <Text style={styles.metricValue}>{data.totals.impressions.toLocaleString()}</Text>
          <Text style={styles.metricLabel}>Total Impressions</Text>
        </View>
        <View style={styles.metricCard}>
          <Text style={styles.metricValue}>
            {(data.totals.likes + data.totals.retweets + data.totals.replies).toLocaleString()}
          </Text>
          <Text style={styles.metricLabel}>Total Engagements</Text>
        </View>
        <View style={styles.metricCard}>
          <Text style={styles.metricValue}>{data.totals.linkClicks.toLocaleString()}</Text>
          <Text style={styles.metricLabel}>Link Clicks</Text>
        </View>
      </View>

      {/* Secondary Metrics */}
      <View style={{ flexDirection: 'row', justifyContent: 'space-around', marginBottom: 20, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' }}>
        <Text style={styles.tweetStat}>Likes: {data.totals.likes.toLocaleString()}</Text>
        <Text style={styles.tweetStat}>Retweets: {data.totals.retweets.toLocaleString()}</Text>
        <Text style={styles.tweetStat}>Replies: {data.totals.replies.toLocaleString()}</Text>
      </View>

      {/* Top Tweets */}
      <Text style={styles.sectionTitle}>Top Performing Tweets</Text>
      
      {data.topTweets.map((tweet, i) => (
        <View key={i} style={styles.tweetRow}>
          <Text style={styles.tweetContent}>{tweet.content}</Text>
          <View style={styles.tweetMeta}>
            <Text style={styles.tweetStat}>👁 {tweet.impressions.toLocaleString()}</Text>
            <Text style={styles.tweetStat}>❤️ {tweet.likes.toLocaleString()}</Text>
            <Text style={styles.tweetStat}>🔁 {tweet.retweets.toLocaleString()}</Text>
            <Text style={styles.tweetStat}>📅 {new Date(tweet.fetchedAt).toLocaleDateString()}</Text>
          </View>
        </View>
      ))}

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by AstroPost • www.astropost.com
      </Text>
    </Page>
  </Document>
);
