/**
 * Service Catalog — Route Integration Tests
 *
 * HTTP-layer integration tests that verify plan gates at the network level
 * by hitting actual API endpoints against a running dev server.
 *
 * Prerequisites:
 *   1. pnpm seed:test-accounts — generates TEST_TOKENS.json at repo root
 *   2. pnpm dev — starts the Next.js dev server at http://localhost:3000
 *
 * Run:
 *   RUN_INTEGRATION_TESTS=1 pnpm test -- src/lib/services/__tests__/service-catalog/route-integration.test.ts
 *
 * Optional:
 *   TEST_BASE_URL — base URL of the running server (default: http://localhost:3000)
 *
 * Design:
 *   - Tests only GATED services (those with a `gate` field in the config).
 *     Ungated services always return 200/201 for everyone — implicitly verified
 *     by the gate-unit test suite and prod-smoke test suite.
 *   - For each service, tests against all 5 plan types.
 *   - Tolerates non-gate failures (401, 404, 422, 429) — we're testing PLAN GATE
 *     enforcement, not whether the full API works end-to-end.
 *   - Key assertions: denied plans must NOT get 200; allowed plans must NOT get 402.
 *   - Skips endpoints that require multipart uploads, OAuth flows, Stripe keys,
 *     or destructive operations.
 */

import { readFileSync, existsSync } from "fs";
import { resolve } from "path";
import { describe, it, expect, beforeAll } from "vitest";
import {
  GATED_SERVICES,
  ALL_PLANS,
  type PlanType,
  type ServiceExpectation,
} from "./service-catalog.config";

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const RUN = process.env.RUN_INTEGRATION_TESTS === "1";
const BASE_URL = (process.env.TEST_BASE_URL ?? "http://localhost:3000").replace(/\/$/, "");

// ---------------------------------------------------------------------------
// Token loading — reads TEST_TOKENS.json generated by pnpm seed:test-accounts
// ---------------------------------------------------------------------------

interface TokenEntry {
  plan: string;
  userId: string;
  email: string;
  token: string;
}

type TokenMap = Map<PlanType, TokenEntry>;

function loadTokens(): TokenMap {
  const map = new Map<PlanType, TokenEntry>();
  const tokenPath = resolve(process.cwd(), "TEST_TOKENS.json");

  if (!existsSync(tokenPath)) {
    return map;
  }

  try {
    const raw = JSON.parse(readFileSync(tokenPath, "utf-8")) as TokenEntry[];
    for (const entry of raw) {
      if (ALL_PLANS.includes(entry.plan as PlanType)) {
        map.set(entry.plan as PlanType, entry);
      }
    }
  } catch {
    // parse failure — map stays empty, beforeAll will report the error
  }

  return map;
}

const tokens = loadTokens();

// ---------------------------------------------------------------------------
// Skip list — endpoints that cannot be tested with simple JSON fetch
// ---------------------------------------------------------------------------

interface SkipEntry {
  route: string;
  method: string;
  reason: string;
}

const SKIP_INTEGRATION: SkipEntry[] = [
  { route: "/api/media/upload", method: "POST", reason: "multipart form-data" },
  { route: "/api/x/accounts", method: "POST", reason: "requires X OAuth flow" },
  { route: "/api/x/accounts/sync", method: "POST", reason: "requires connected X account" },
  { route: "/api/billing/checkout", method: "POST", reason: "requires Stripe key" },
  { route: "/api/billing/portal", method: "POST", reason: "requires Stripe customer" },
  { route: "/api/billing/change-plan", method: "POST", reason: "requires Stripe subscription" },
  { route: "/api/billing/change-plan/preview", method: "POST", reason: "requires Stripe key" },
  { route: "/api/billing/validate-promo", method: "POST", reason: "requires Stripe key" },
  { route: "/api/user/delete", method: "DELETE", reason: "destructive operation" },
  { route: "/api/stripe", method: "POST", reason: "requires Stripe key" },
];

const skipKey = (route: string, method: string) => `${method}:${route}`;
const skipKeys = new Set(SKIP_INTEGRATION.map((s) => skipKey(s.route, s.method)));

// ---------------------------------------------------------------------------
// Filter gated services to those testable via simple JSON fetch
// ---------------------------------------------------------------------------

const TESTABLE_SERVICES: ServiceExpectation[] = GATED_SERVICES.filter(
  (s) => s.route && s.method && !skipKeys.has(skipKey(s.route, s.method))
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function safeBodySnippet(res: Response, maxLen = 200): Promise<string> {
  try {
    const text = await res.text();
    return text.slice(0, maxLen);
  } catch {
    return "(could not read body)";
  }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("Service Catalog — Route Integration Tests", () => {
  // The entire suite is gated behind RUN_INTEGRATION_TESTS=1.
  // When the env var is not set, this block appears as SKIPPED in vitest output
  // with a clear message about how to enable it.
  describe.skipIf(!RUN)(
    "Route-level plan gate enforcement (set RUN_INTEGRATION_TESTS=1 to run)",
    () => {
      // ── Pre-flight checks ───────────────────────────────────────────────────

      beforeAll(() => {
        if (tokens.size === 0) {
          throw new Error(
            "TEST_TOKENS.json not found at repo root.\n" + "Run: pnpm seed:test-accounts"
          );
        }
        if (tokens.size < ALL_PLANS.length) {
          const missing = ALL_PLANS.filter((p) => !tokens.has(p));
          throw new Error(
            `TEST_TOKENS.json is missing tokens for plans: ${missing.join(", ")}.\n` +
              "Run: pnpm seed:test-accounts"
          );
        }
      });

      it("has tokens for all 5 plan types", () => {
        for (const plan of ALL_PLANS) {
          expect(tokens.has(plan), `Missing token for plan: ${plan}`).toBe(true);
        }
      });

      it("has testable gated services", () => {
        expect(TESTABLE_SERVICES.length, "No testable gated services found").toBeGreaterThan(0);
      });

      it("prints coverage summary", () => {
        const byCategory = new Map<string, number>();
        for (const svc of TESTABLE_SERVICES) {
          byCategory.set(svc.category, (byCategory.get(svc.category) ?? 0) + 1);
        }
        const categoryLines = [...byCategory.entries()]
          .map(([cat, count]) => `    ${cat}: ${count} services`)
          .join("\n");

        const skippedCount = GATED_SERVICES.length - TESTABLE_SERVICES.length;

        console.warn(
          `\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n` +
            `  Route integration test coverage\n` +
            `  Server:       ${BASE_URL}\n` +
            `  Services:     ${TESTABLE_SERVICES.length} testable (${skippedCount} skipped)\n` +
            `  Plans:        5 (all configured)\n` +
            `  Test cases:   ${TESTABLE_SERVICES.length * ALL_PLANS.length}\n` +
            `${categoryLines}\n` +
            `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`
        );
        expect(true).toBe(true);
      });

      // ── Per-service test matrix ─────────────────────────────────────────────
      // For each gated service: 5 plan tests = service.access[plan] → 200 or 402

      describe.each(TESTABLE_SERVICES)("$name ($method $route) [gate: $gate]", (service) => {
        it.each(ALL_PLANS.map((p) => [p, service.access[p]] as [PlanType, boolean]))(
          "plan=%s → expected allowed=%s",
          async (plan: PlanType, expectedAllowed: boolean) => {
            const tokenEntry = tokens.get(plan);
            if (!tokenEntry) {
              // Should not happen — beforeAll checks this, but defensive
              console.warn(`No token for plan: ${plan}, skipping`);
              return;
            }

            const fetchOptions: RequestInit = {
              method: service.method ?? "GET",
              headers: {
                Cookie: `better-auth.session_token=${tokenEntry.token}`,
                "Content-Type": "application/json",
              },
              redirect: "manual",
            };

            // Attach body for mutation endpoints
            if (service.method && service.method !== "GET") {
              fetchOptions.body = service.minimalPayload
                ? JSON.stringify(service.minimalPayload)
                : "{}";
            }

            let res: Response;
            try {
              res = await fetch(`${BASE_URL}${service.route}`, fetchOptions);
            } catch (err) {
              if (
                err instanceof Error &&
                (err.message.includes("ConnectionRefused") ||
                  err.message.includes("ECONNREFUSED") ||
                  err.message.includes("fetch failed"))
              ) {
                throw new Error(
                  `Server not running at ${BASE_URL}. Start with: pnpm dev\n` +
                    `Error: ${err.message}`
                );
              }
              throw err;
            }

            const bodySnippet = await safeBodySnippet(res);

            if (expectedAllowed) {
              // Allowed plan: response must NOT be 402 (gate denying access).
              // Other statuses (200, 201, 401, 404, 422, 429) are acceptable —
              // they reflect infrastructure issues (expired token, missing
              // resource, validation failure, rate limit) not gate enforcement.
              expect(
                res.status,
                `"${service.name}" (${service.method} ${service.route}) — ` +
                  `plan "${plan}" should have access.\n` +
                  `  Expected: not 402 (gate says allowed)\n` +
                  `  Got:      ${res.status}\n` +
                  `  Body:     ${bodySnippet}`
              ).not.toBe(402);
            } else {
              // Denied plan: response must be 402 (gate enforcing) or
              // 401 (expired/invalid token — infrastructure, not gate failure).
              // 200 would mean the gate is incorrectly allowing access.
              expect(
                [402, 401],
                `"${service.name}" (${service.method} ${service.route}) — ` +
                  `plan "${plan}" should be denied access.\n` +
                  `  Expected: 402 | 401\n` +
                  `  Got:      ${res.status}\n` +
                  `  Body:     ${bodySnippet}`
              ).toContain(res.status);
            }
          },
          15000 // 15s timeout per test (each makes exactly 1 HTTP request)
        );
      });
    }
  );
});
